pipeline {
 agent any

stages {
    stage('Checkout') {
        steps {
            echo 'Checking out...'
                git credentialsId: 'ineslourencom',
                url: 'https://bitbucket.org/ineslourencom/devops-21-22-atb-1211767/'
        }
    }

    stage('Assemble') {
        steps {
            dir ("CA2/Part1/gradle_basic_demo"){
            echo 'Assembling...'
            sh './gradlew assemble'
            }
        }
    }

    stage('Test') {
        steps {
            dir ("CA2/Part1/gradle_basic_demo"){
            echo 'Testing...'
            sh './gradlew test'
            junit 'build/test-results/test/*.xml'
            }
        }
    }

    stage('Archiving') {
        steps {
            echo 'Archiving...'
            dir ("CA2/Part1/gradle_basic_demo"){
                archiveArtifacts 'build/distributions/*'
            }
        }
    }

 }
}